# Generated by Django 5.2.4 on 2025-07-22 17:34

import auth_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=auth_app.models.get_default_expiry),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['email', 'created_at'], name='auth_app_ot_email_5b873b_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['email', 'is_used', 'expires_at'], name='auth_app_ot_email_dc144d_idx'),
        ),
    ]
